apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  # labels:
  #   run: my-app
spec:
  # type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app
  type: ClusterIP