apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: udagram-api
        image: ctala/udagram-api
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080    
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: POSTGRES_HOST
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: POSTGRES_DB
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: JWT_SECRET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: AWS_REGION
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: AWS_BUCKET